name: Ejecutar scraper

on:
  schedule:
    - cron: '*/5 * * * *'  # Ejecuta cada 5 minutos
  workflow_dispatch:  # Permite ejecutarlo manualmente desde GitHub

concurrency:
  group: scraper
  cancel-in-progress: true  # Cancela la ejecución anterior si una nueva empieza

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Instalar dependencias
        run: |
          pip install selenium webdriver-manager

      - name: Ejecutar script con límite de tiempo
        run: timeout 180s python scraper.py  # 3 minutos de ejecución máxima

      - name: Verificar si la base de datos existe
        run: ls -l subastas.db || echo "⚠️ Archivo subastas.db no encontrado"

      - name: Subir base de datos actualizada
        if: success()  # Asegura que el paso anterior no falló
        uses: actions/upload-artifact@v4
        with:
          name: subastas-database
          path: subastas.db
